### ISSUE TITLE
Syntax error in RMS.as

### ISSUE THREAD

**Issue by roncli** [GreepTheSheep/openplanet-MXRandom#112]
**Describe the bug**
Commit 901afa1bfe416971d953851524d2dcc74f82e7e3 introduced a syntax error that breaks RMS.as.  An #endif is present, but no matching #if exists.

**To Reproduce**
1. Start Trackmania
2. Once all is loaded, check the OpenPlanet logs
3. Error shows there is an unmatched #endif in line 68 (it does not say the file, I had to look!)

**Expected behavior**
Syntax error should be fixed, and no error should be present.

**Screenshots**
n/a

**Openplanet (please complete the following information):**
Issue is not related to Openplanet.
Version: 1.26.4
Game: TM2020

**Additional context**
n/a

**Comment by GreepTheSheep** [comment]
Found it: https://github.com/GreepTheSheep/openplanet-MXRandom/blob/41c041ea6943117c7719639c7861d454d7e461a9/src/Utils/RMC/RMS.as#L68C1-L68C7
I don't know why I left a #endif here, will take a look later

**Comment by EdVraz** [comment]
I seem to have deleted the [`#if TMNEXT` but accidentally kept the `#endif` for it here](https://github.com/GreepTheSheep/openplanet-MXRandom/pull/111/files#diff-ca2beabc8efa8352e4181005c96210355c4e7d5154d03536ee18df5e0604fb4eL66-R69). I didn't notice because when I tested the changes everything worked fine, which it still does from what I can tell? I can play RMC and RMS without issues even though the syntax error is present.
