### ISSUE TITLE
RMT kept "switching" to the same map repeatedly

### ISSUE THREAD

**Issue by Wain4** [GreepTheSheep/openplanet-MXRandom#88]
An AT was beaten, then RMT "switched maps", but the next map was the same as the previous, and the room timer started at 0:02. After the room timer expired, it switched to the same map again.
In the voting menu, the server's map list contained the stuck map and the lobby map.

VOD: https://www.twitch.tv/videos/1847061503?t=2h46m8s

Lars speculated that this might happen when RMT randomly picks the same map twice in a row.

**Comment by Wain4** [comment]
VOD with log: https://www.twitch.tv/videos/1852933721?t=1h47m21s

**Comment by Wain4** [comment]
In the log from 2 weeks ago, the plugin found a next map. The map looked normal, but it wasn't uploaded to nadeo services. Any chance that can be an issue?
In today's occurrence, the plugin found a map from xk.io, the map is unlisted on TMX and has "WIP" in the name. I can't access the map at all.
Log from today:
![image](https://github.com/GreepTheSheep/openplanet-MXRandom/assets/133581083/f0b17687-8390-4363-af15-600a40b45500)

**Comment by GreepTheSheep** [comment]
@Wain4 this is not the subject, can you make another issue about this ?

**Comment by Wain4** [comment]
XertroV made one already: #95
Not sure how this is not the subject though, both cases look the same (room keeps switching to the same map).

**Comment by XertroV** [comment]
> In today's occurrence, the plugin found a map from xk.io, the map is unlisted on TMX and has "WIP" in the name. I can't access the map at all.

This can happen when someone uploads a map and later removes it. Basically my server cached it but tmx doesn't offer the download link anymore. One solution is to use the CGF mirror which usually downloads maps once they're available. Another solution is loading the map from nadeo if it's uploaded -- since the UID is in the tmx/random response, the map can be checked using core game APIs and then optionally loaded via the URL parameter of the game's map info response. 

So we should be able to solve this case with a combination of those measures.

Additionally, when I implement update scraping from TMX the API should no longer return those maps.

**Comment by Wain4** [comment]
> Additionally, when I implement update scraping from TMX the API should no longer return those maps.

Is this done? GranaDy had this issue today.

I wasn't there to tell him to show the log, and I'm not even sure whether he's using xk or tmx, but what I can see in the VOD is:
The next map is found, it's called "Lost Island", all 3 maps with that name on TMX look normal, and the vote text says "JumpToMapIdent ????" (question marks instead of the map name). https://www.twitch.tv/videos/1871547786?t=2h10m16s

**Comment by XertroV** [comment]
> Is this done? GranaDy had this issue today.

Yes, it's done now. I also check map URLs before redirecting in this order of priority:

1. TMX
2. Nadeo (since it's uploaded to nadeo services)
3. CGF mirror
